image: node:17.6.0

stages:
  - test
  - prepare
  - publish

test:enum-typescript:
  stage: test
  script:
    - cd plugins/only-enum-types
    - yarn
    - yarn build
    - yarn test

test:local-typescript-operations:
  stage: test
  script:
    - cd plugins/local-typescript-operations
    - yarn
    - yarn build
    - yarn test

create_release_mr:
  stage: prepare
  script:
    - yarn
    - yarn changeset version
    - create_and_push_commit
    - create_mr
  only:
    refs:
      - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Version bump/
  when: manual

release_changes:
  stage: publish
  script:
    - set_npm_auth_config
    - yarn
    - yarn changeset publish
  only:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /Version bump/
  when: manual

before_script:
  - set -euxo pipefail
  - . ci-functions.sh
